Pgsql
dmachard/dnstap-receiver pull request #37
Opened 2021-07-19 03:06 UTC by motok

2021-07-19 03:08 UTC, motok commented
Sorry I made a mistake to click 'create pull request'.

2021-07-20 12:10 UTC, dmachard requested changes

2021-07-20 12:31 UTC, motok commented on tests/test_external_config.py
> +        cmd = 'python3 -c "from dnstap_receiver.receiver import start_receiver; start_receiver()" -c ./tests/dnstap_pgsql.conf'
Sorry, it is now on the github.
By the way, I am afraid we need to add a running postgresql to pass this test.
Thanks!

2021-07-24 10:22 UTC, merged

2021-07-25 13:54 UTC, motok commented
Thank you very much and it is running perfectly in my node!